### ISSUE TITLE
✏️ React Native에서 고유 식별자를 안전하게 서버로 전송하기

### ISSUE THREAD

**Issue by BangDori** [CorTorE/blogging-study#4]
### 내용 (한줄 요약)

고유 식별자를 SHA-256 해싱 알고리즘을 사용하여 안전하게 전송하기까지의 문제 해결 과정

### 예상 독자

- 나
   - 클라이언트-서버 통신에서 식별자를 안전하게 전달하기 위한 방법에 대한 글
   - 직면한 상황에 맞춰 해결 방법을 찾아가는 과정을 스스로 점검하기 위함

### 블로그 링크

https://bangdori.kr/posts/sha256-hashing-in-react-native/

**Comment by asuan99** [comment]
글의 구성 상 기존 문제와 여러 해결 방안 중 이를 택한 이유, 그리고 선택하지 않은 방법들의 문제점 및 시각적인 보조 자료가 내용 이해를 더 원할하게 해주는 게 느껴지네요. 

본인의 기존 글에 다른 문서를 참조할 수 있을 듯한 내용은 문장은 연결 링크를 제공해, 본인 글의 유입이 더 많아질 수 있도록 하는 것도 방법이겠네요. 

예상 독자가 '나' 로 설정된 부분은 자기 자신을 스스로 돌아보기 위함이라 작성된 부분은 좋지만, 어떤 상황에서의 '나'를 위한 글인지 다시 한 번 확인해보고, 좀 더 구체화할 필요가 있어 보입니다. 예를 들어, FE 개발자 중에서도, 보안 이슈를 위한 건지, 캐싱 성능 향상의 필요성을 위한 글인지, loading latency를 단축시키기 위한 이슈를 해결하고자 했던건지 등 독자의 범위가 구체성을 띄었으면 좋겠습니다.

**Comment by BangDori** [comment]
> 예상 독자가 '나' 로 설정된 부분은 자기 자신을 스스로 돌아보기 위함이라 작성된 부분은 좋지만, 어떤 상황에서의 '나'를 위한 글인지 다시 한 번 확인해보고, 좀 더 구체화할 필요가 있어 보입니다. 예를 들어, FE 개발자 중에서도, 보안 이슈를 위한 건지, 캐싱 성능 향상의 필요성을 위한 글인지, loading latency를 단축시키기 위한 이슈를 해결하고자 했던건지 등 독자의 범위가 구체성을 띄었으면 좋겠습니다.

좋은 의견 감사합니다. 확실히 이 부분에 대해서는 미흡하게 작성한 것 같네요. 구체화를 하자면 **클라이언트-서버 통신에서 식별자를 안전하게 전달하기 위한 방법에 대한 글**이 될 것 같습니다. 수정해두겠습니다!

**Comment by psychology50** [comment]
글 구성은 상당히 좋은데, 내용에 대한 의문점들 위주로 적었어용.  
혹시 제가 작성한 게 다소 4가지 없어 보인다면, 그저 제 영어 실력이 미숙한 것일 뿐임다..

---

This post effectively engages readers by   
- using visuals and short code snippets.
- Clearly structured and divided chapters.
  
However, I have a few questions about the content

### Certainly Identification Method?
- You aim to identify unauthenticated users, but why is this necessary?
- If clients choose not to log in, it indicates they wish to keep their information private, which might fall outside our authority.
- To make this post more compelling, consider explaining "why identifying unauthenticated users is essential."

Apple's KeyChain can be an alternative to cookies for storing user identification, though it's not guarantee permanent. 

### UUID is effectively unique
- According to the [wiki](https://en.wikipedia.org/wiki/Universally_unique_identifier), the probability of a UUID collision is negligible
   ![image](https://github.com/user-attachments/assets/003f63c4-0d03-4dc9-8b19-a065d23424c1)
- However, using UUID v1 raises security concerns because it includes the MAC address, exposing sensitive device details.

### Is `ANDROID_ID` unique?
   ![image](https://github.com/user-attachments/assets/55d76e7e-8239-4567-9f2c-8baf38776e33)

iOS offers a similar feature: [IDFV (identifierForVender)](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor)
 
   ![image](https://github.com/user-attachments/assets/fdfa6e87-6433-41ee-a6ee-f59135e1633e)

Although both claim to provide unique identifiers, they can change under certain conditions.  
Neither is entirely reliable for long-term identification.

### Why Can’t We Identify Unauthenticated Users?
- Technically, it’s possible to identify devices using their MAC addresses.
- However, this violates privacy and often contradicts legal and ethical guidelines. "Unauthenticated" implies users don’t wish to reveal their information, making identification both undesirable and inappropriate.
- As I mentioned earlier, the post would benefit from discussing why we need to identify unauthenticated users even after they delete the app. Without this reasoning, it might be better to shift focus from technical concerns to limiting the services we provide to unauthenticated users from a service perspective.

**Comment by BangDori** [comment]
@psychology50 앱 스토어 심사급의 디테일한 리뷰에 감사드립니다!!!!!!!!!!!!!!!!

처음에는 **API 요청 제한을 통해 서버의 트래픽 부하를 조절하는 방법**에 대한 내용을 담고자 했으나, 서버 측 구현에 직접적으로 관여하지 않다 보니 글이 자연스럽게 이어지지 않았고, 결국 **클라이언트 측에서 고유 식별자를 안전하게 서버로 전송하는 방법**으로 내용이 변경되었던 것 같습니다. 글을 읽으면서 많은 혼란이 있었을텐데 끝까지 읽어 주셔서 very very Thank you...!!!!!@@@...@!!#  😊😊

우선 리뷰에서 지적해주신 것처럼, "인증되지 않은 사용자를 식별해야 하는 이유"와 "변경 가능성이 있는 ANDROID_ID를 사용하는 이유", 그리고 "IDFV와 같은 노출되어서는 안 되는 고유 식별자를 사용하는 이유"에 대한 설명이 부족했던 점이 글의 설득력을 상당히 떨어뜨린 것 같습니다. 

이에 대해 좀 간결히 설명드리자면 API 요청 제한을 통해 서버의 트래픽 부하를 조절하기 위해서는 **사용자가 앱을 사용하는 동안 트래픽 제한을 위한 단기적인 식별자가 필요**하며, 이 **단기적인 식별자를 클라이언트에서 서버로 안전하게 전달하는 방법을 강조**하고 싶었습니다.

사실 해당 글을 작성한 이유가 이 글을 읽는 독자를 설득하기 위함보다는 **직면한 상황에 맞춰 해결 방법을 찾아가는 과정을 스스로 점검하기 위함**이긴 했습니다. 하지만 이렇게 디테일한 리뷰를 듣고 나니 지금까지 작성한 포스팅에 대해 다시 되돌아보는 계기가 되는 것 같네요. 귀중한 피드백 덕분에 많은 점을 배우고, 스스로를 되돌아볼 수 있었습니다. 감사합니다 ㅎㅎ 😻

**Comment by psychology50** [comment]
Actually, your concern is addressed on the server side. 😂

Backend developers implement `Rate Limiters`, so the client-side only needs to handle request limiting using techniques like `throttling` or `debouncing`.  
If you'd like to dive deeper, feel free to check out [my post](https://jaeseo0519.tistory.com/391)

**Comment by BangDori** [comment]
thank you for sharing~

생각해보니 클라이언트단에서 발생하는 대부분의 시나리오가 쓰로틀링이나 디바운싱 기법 그리고 캐싱을 활용하여 해결이 가능하겠군요. 

공유해주신 포스팅 읽으면서 신기한 알고리즘들을 많이 접할 수 있게 되었고(진짜 이런 거 어떻게 알아오시는건지), TCP & UDP부터 흐름 제어 혼잡 제어까지 다시 복기할 수 있는 시간이 되었네요 ㅎㅎ
