### ISSUE TITLE
✏️ React Native Fastlane Discord 알림 연동하기

### ISSUE THREAD

**Issue by BangDori** [CorTorE/blogging-study#8]
### 내용 (한줄 요약)

앱 배포 알림 자동화를 통해 생산성 개선하기

### 예상 독자

앱 개발 및 배포 자동화에 관심이 있는 독자

### 블로그 링크

https://bangdori.kr/posts/fastlane_and_discord/

**Comment by psychology50** [comment]
Did you previously explain `Fastlane`?  
I understood because I’ve used it before, but someone unfamiliar with `Fastlane` might struggle to follow.  
I don’t think it’s necessary to go in-depth about what `Fastlane` is, but providing a link (e.g., to the official documentation) could help readers understand its concept.  

When I first learned about `Fastlane`, the hardest part was understanding what it is and how or where it’s used.  
Most blog posts don’t include a diagram showing where it operates—and yours doesn’t either. If possible, adding a more detailed flow diagram would improve clarity.  

Lastly, a small suggestion: 
Since Unit 2 covers automation notifications, error notifications might be better separated into Unit 3. 

--- 

혹시 이전에 `Fastlane`에 대해 정리한 적이 있나요?  
전 사용해본 적이 있어서 이해할 수 있었지만, Fastlane이 뭔지 아예 모르는 사람이 보기엔 많이 어려울 거 같아요.  
(내용이 워낙 단순한 지라, 이미 아는 사람보다는 fastlane이 뭔지 조차 모르는 사람이 많이 찾을 것 같아서요.)  
물론, `Fastlane`이 뭔지 상세히 설명할 필요는 없다고 생각하지만, 개념이 뭔지 찾을 수 있는 링크(ex 공식문서)를 첨부해주시면 좀 더 도움이 되지 않을까 싶긴 합니다.  
(근데 사실 저도 github actions로 파이프라인 구축할 때, 모르면 공부하고 오라고 내쫒았었음 ㅋㅋㅋ)  

제가 `Fastlane`을 아예 모를 때 가장 어려웠던 점은 그게 무엇이고, 언제 어디서 사용하냐는 것이었습니다.  
왜냐면 블로그 포스팅들이 죄다 fastlane이 어디서 동작하는 지 보여주질 않고 있었거든요.  
만약 가능하다면, 다이어그램으로 보다 명시적으로 흐름을 보여줄 수 있었으면 좋았을 것 같습니다.  

마지막으로 이거 사소한 의견인데,  
에러 알림 처리는 Unit 3로 분리했어도 괜찮았을 거 같아용!

**Comment by youngsu5582** [comment]
블로그 적인 내용은 간단해서 크게 피드백 할 부분이 없는거 같네용.

개발자 생산성 관점에서
`fastlane 이 무슨 정보를 주는지` + `Discord 가 어떤 상호작용을 가능하게 해주는지` 는 모르겠지만
바로가기 버튼( 앱 스토어, 깃허브, 사이트 주소) 등을 통해 추가적인 기능을 제공하면 더 좋은 기능이 될 거 같네용 🙂

**Comment by BangDori** [comment]
@psychology50

이번 포스팅은 정말 단순하게 fastlane을 이용한 알림 자동화에 대한 포스팅을 하려고 했던터라 fastlane에 대한 내용은 일부러 제외하긴 했습니다. 근데 리뷰어님이 말씀해주신 것처럼 fastlane에 대해 알지 못하는 사람을 위해 간단하게 내용을 요약한다거나, 공식 문서에 대한 링크를 추가하면 더 좋을 것 같네요!

에러 알림 처리 부분은 분리하기에는 내용이 너무 짧다고 느껴지기도 했고, 성공 알림 처리와 함께 연결되게 작성하는 것도 나쁘지 않다고 생각했는데   초기 설정 단계 / 성공 & 에러 알림 처리를 아예 나누는 것이 더 좋을까요?

**Comment by psychology50** [comment]
> 에러 알림 처리 부분은 분리하기에는 내용이 너무 짧다고 느껴지기도 했고, 성공 알림 처리와 함께 연결되게 작성하는 것도 나쁘지 않다고 생각했는데   초기 설정 단계 / 성공 & 에러 알림 처리를 아예 나누는 것이 더 좋을까요?

솔직히 개인 취향이라고 생각해여.  
전 그냥 하나의 주제에선 하나의 내용만 다루는 걸 선호하는데, 병준님이 생각하기에 그게 더 적절하다면 문제라고 할 만한 내용은 아닌 거죠.  

저도 여기서 글 구성으로 피드백 받으면 신경 쓰려고는 하는데, 제 스타일이랑 너무 안 맞으면 걍 무시하거든여.  
뭐든 본인 스타일을 뚝심있게 유지하는 것도 중요한 법이죠. ㅋㅋ  

근데 파이프라인 구축할 때 다이어그램 넣는 건 필요할 거 같아요.  
저 예전에 작성한 포스팅에 이거 안 넣어서, 최근에 지적받았거든여 ㅋㅋㅋㅋㅋ

**Comment by BangDori** [comment]
@psychology50 

아 확실히 파이프라인에 대한 다이어그램은 추가하는 게 좋겠네요ㅋㅋㅋ

다이어그램 하나 만으로 내가 하려는 게 뭔지를 보여줄 수 있기도 하고, 영수님이 말씀해주신 부분도 어느정도 해결될 수 있을 것 같아요
> fastlane 이 무슨 정보를 주는지 + Discord 가 어떤 상호작용을 가능하게 해주는지

좋은 의견 감사합니다~~~
